title: "Sharon Brizinov"
url: "https://sharonbrizinov.com"
desc: "Sharon Brizinov is a security researcher specializing in vulnerability research and OT/IoT security, with over 200 CVEs."
keywords: "security,researcher,developer,programmer"
author: "Sharon Brizinov"
baseurl: "https://sharonbrizinov.com"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://sharonbrizinov.com"
footer_text: "Sharon Brizinov"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CVEs"
   link: "cves"
 - name: "Contact"
   link: "contact"