title: "Sharon Brizinov"
url: "https://sharonbrizinov.com"
desc: "I am an Information Security specialist. My interests range from technology to science."
keywords: "security,researcher,developer,programmer"
author: "Sharon Brizinov"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://sharonbrizinov.com"
footer_text: "Sharon Brizinov"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CVEs"
   link: "cves"
 - name: "Contact"
   link: "contact"
